post_listing:
  list_title: "Stories, Technology and Philosophy"
  group_by: year
  list_format: "{post_date} ~ [{post_title}]({post_link}) {post_category_tag}"
  per_page: 15
  newer_link_text: "← Newer posts"
  older_link_text: "Older posts →"
post_date_format:
  on_list: "%d-%b"
  on_post: "%d-%m-%Y"
